# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-02 16:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EgeMathTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_num', models.PositiveIntegerField()),
                ('task_num', models.PositiveIntegerField()),
                ('question_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('question_text', models.TextField(blank=True, null=True)),
                ('correct_answer', models.CharField(max_length=20)),
                ('explanation_video', models.URLField(blank=True, null=True)),
                ('explanation_text', models.TextField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_num', models.PositiveIntegerField()),
                ('task_num', models.PositiveIntegerField()),
                ('answer', models.CharField(blank=True, max_length=20, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
