# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-02 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egemath', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egemathtest',
            name='author',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='author',
            field=models.CharField(max_length=30),
        ),
    ]
