# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-14 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egemath', '0003_auto_20170715_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egemathtest',
            name='question_image',
            field=models.ImageField(blank=True, null=True, upload_to='egetest'),
        ),
    ]
