# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-27 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egemath', '0005_egemathtest_answer_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='egemathtest',
            name='access_level',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='egemathtest',
            name='answer_text1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='egemathtest',
            name='answer_text2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='egemathtest',
            name='answer_text3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='egemathtest',
            name='answer_text4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='egemathtest',
            name='question_text1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='egemathtest',
            name='question_text2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='egemathtest',
            name='question_text3',
            field=models.TextField(blank=True, null=True),
        ),
    ]
